#!/bin/sh

# Workaround for https://bugs.winehq.org/show_bug.cgi?id=50257
export LD_32_BIND_NOW=1

TARGET="`realpath $0`"

LOCALBASE=${TARGET%/*}/..
BINNAME=${TARGET##*/}

if [ -z "$__BINBOUNCE_BOOTSTRAP" ]
then
  export LIBGL_DRIVERS_PATH=$LOCALBASE/lib32/dri
  if [ `uname -p` = i386 ]
  then
    export LD_LIBRARY_PATH="$LOCALBASE/lib32":"$LOCALBASE/lib32/wine":"$LD_LIBRARY_PATH":"$LOCALBASE/lib32/.libGL"
    export LD_LIBRARY_PATH_RPATH=y
  else
    export LD_32_LIBRARY_PATH="$LOCALBASE/lib32":"$LOCALBASE/lib32/wine":"$LD_32_LIBRARY_PATH":"$LOCALBASE/lib32/.libGL":/usr/lib32
    export LD_32_LIBRARY_PATH_RPATH=y
  fi
  export PATH="$LOCALBASE/bin32":"$PATH"
  export __BINBOUNCE_BOOTSTRAP="1"

  WINE32_VERSION=`$LOCALBASE/bin32/wine --version`
  WINE64_VERSION=`wine64 --version`
  if [ "$WINE32_VERSION" != "$WINE64_VERSION" ]
  then
    echo "Please, make sure that wine [$WINE32_VERSION] and wine64 [$WINE64_VERSION] versions match each other."
    exit 1
  fi
fi

exec "$LOCALBASE/bin32/$BINNAME" "$@"
