PORTNAME=	mod_php
DISTVERSION=	${PHP_DEFAULT}
CATEGORIES=	www devel 
MASTER_SITES=	# empty
DISTFILES=	# empty
EXTRACT_ONLY=	# empty

MAINTAINER=	ports@malavon.eu
COMMENT=	Meta-port for mod_php
WWW=		https://www.php.net/

LICENSE=	PHP301

USES=		cpe php:mod

USES=		metaport

NO_ARCH=	yes
NO_BUILD=	yes

.include <bsd.port.mk>
