# $FreeBSD$

PORTNAME=	restclient-cpp
PORTVERSION=	0.9.2
PORTREVISION=	0
DISTVERSIONPREFIX=	${PORTNAME}-
CATEGORIES=	devel

MAINTAINER=	@FreeBSD.org
COMMENT=	

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake compiler:c++14-lang

BUILD_DEPENDS=	rapidjson>=1.1.0_4:devel/rapidjson

LIB_DEPENDS=  	

USE_GITHUB=	yes
GH_ACCOUNT=	jgaa
GH_PROJECT=	restc-cpp
GH_TAGNAME=	staging

.include <bsd.port.mk>
